### Rota GET

GET http://localhost:3030/perfiloficial
Content-Type: application/json


###


### Rota GET

GET http://localhost:3030/usuario
Content-Type: application/json


###


### POST

POST http://localhost:3030/verificar
Content-Type: application/json

{
    "numero_bi_enc": "123456789LA045"
}


###


### POST

POST http://localhost:3030/perfiloficial
Content-Type: application/json

{
    "kyc": true
}



###


POST http://localhost:3005/criar/senha
Content-Type: application/json

{
    "senha_hash": "013",
    "professor_id": 12
}

###

POST http://localhost:3005/criar/senha/aluno
Content-Type: application/json

{
    "senha_hash": "006",
    "aluno_id": 14
}

###/autenticar/aluno



POST http://localhost:3005/autenticar/professor
Content-Type: application/json

{
   "senha_hash": "009",
  
   "disciplina": "Projeto Tecnológico"
}


###


POST http://localhost:3005/autenticar/aluno
Content-Type: application/json

{
   "senha_hash": "aluno1",
  
   "turma": "Turma A"
}

###


GET http://localhost:3005/notas
Content-Type: application/json

###


GET http://localhost:3005/notas/professor
Content-Type: application/json

###


GET http://localhost:3005/buscar/alunos
Content-Type: application/json






